pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "panduass/springboot-openshift:v3"
        DOCKER_CREDENTIALS_ID = "docker-hub"
        GITHUB_REPO = "https://github.com/panduass/springboot-openshift-v3"
        OPENSHIFT_PROJECT = "panduass-dev"
        OPENSHIFT_SERVER = "https://api.rm1.0a51.p1.openshiftapps.com:6443"
        
        OPENSHIFT_TOKEN = credentials('openshift-v3')
        WEBHOOK_URL = "https://9180f8239a25.ngrok-free.app/github-webhook/"
    }

    stages {
        stage('Clone GitHub Repo') {
            steps {
                git url: "${env.GITHUB_REPO}", branch: 'master'
            }
        }

        stage('Set Docker Tag') {
            steps {
                script {
                    env.DOCKER_TAG = "v${env.BUILD_NUMBER}"
                    echo " Docker tag: ${env.DOCKER_TAG}"
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    echo "Building Docker image: ${DOCKER_IMAGE}:${env.DOCKER_TAG}"
                    docker.build("${DOCKER_IMAGE}:${env.DOCKER_TAG}", "-f java_openshift/Dockerfile java_openshift")
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    echo "Pushing Docker image to Docker Hub"
                    docker.withRegistry('', "${DOCKER_CREDENTIALS_ID}") {
                        docker.image("${DOCKER_IMAGE}:${env.DOCKER_TAG}").push()
                    }
                }
            }
        }

        stage('Generate Deployment YAML') {
            steps {
                script {
                    def baseYaml = readFile('java_openshift/base-deployment.yaml')
                    def updatedYaml = baseYaml.replaceAll(
                        "image:\\s+panduass/spring-openshift:latest",
                        "image: ${DOCKER_IMAGE}:${env.DOCKER_TAG}"
                    )
                    writeFile file: 'deployment.yaml', text: updatedYaml
                    echo "YAML updated with image tag: ${env.DOCKER_TAG}"
                }
            }
        }

        stage('Apply to OpenShift') {
            steps {
                script {
                    sh """
                    oc login ${OPENSHIFT_SERVER} --token=${OPENSHIFT_TOKEN} --insecure-skip-tls-verify
                    oc project ${OPENSHIFT_PROJECT}
                    oc apply -f deployment.yaml
                    """
                }
            }
        }
    }

    post {
        success {
            script {
                def route = sh(script: "oc get route springboot-app -o jsonpath='{.spec.host}'", returnStdout: true).trim()
                def routeUrl = "http://${route}"
                echo "Deployment successful! Access your app at: ${routeUrl}"
            }
        }

        failure {
            script {
                def payload = """
                {
                  "text": "Jenkins deployment failed for *springboot-app* in build #${env.BUILD_NUMBER}",
                  "attachments": [
                    {
                      "color": "danger",
                      "title": "Job: ${env.JOB_NAME}",
                      "title_link": "${env.BUILD_URL}",
                      "text": "Check the Jenkins logs for more details."
                    }
                  ]
                }
                """
                writeFile file: 'alert-payload.json', text: payload
                sh "curl -X POST -H 'Content-type: application/json' --data @alert-payload.json ${env.WEBHOOK_URL}"
            }
        }
    }
}